<a href="https://colab.research.google.com/github/ruveydee/AboutStatistic/blob/main/Stats_Assign_(Central_Tendency%26_Dispersion).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats
import statistics

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

np.random.normal(loc=0.0, scale=1.0, size=None)  #you need to modify this code.

loc will be equal to mean, scale will be equal to std deviation, size will be equal to sample size.

In [4]:
samples = np.random.normal(loc=100, scale=15, size=1000)

Compute the **mean**, **median**, and **mode**

In [7]:
mean = np.mean(samples)
median =np.median(samples)
mode = stats.mode(samples)

print(f"Mean value of samples: {mean}")
print(f"Median value of samples: {median}")
print(f"Mode value of samples: {mode}")

Mean value of samples: 100.07170248861537
Median value of samples: 100.02445064865117
Mode value of samples: ModeResult(mode=array([41.9474214]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [8]:
min = min(samples)
max = max(samples)
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = q3 - q1

print(f"Min value of samples: {min}")
print(f"Max value of samples: {max}")
print(f"q1 value of samples: {q1}")
print(f"q3 value of samples: {q3}")
print(f"IQR value of samples: {iqr}")

Min value of samples: 41.947421398224506
Max value of samples: 147.03537024773001
q1 value of samples: 89.7822769435487
q3 value of samples: 110.30364138126983
IQR value of samples: 20.521364437721132


Compute the **variance** and **standard deviation**

In [11]:
variance = statistics.variance(samples)
std_dev = statistics.stdev(samples)
print(f"Variance : {variance}")
print(f"standeart devision: {std_dev}")

Variance : 222.4282956797131
standeart devision: 14.914030162223526


In [21]:
#np.std(samples)
#np.var(samples)

Compute the **skewness** and **kurtosis**

You can use [`scipy.stats.skew`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html) and [`scipy.stats.kurtosis`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html)

In [13]:
skewness = stats.skew(samples)
kurtosis = stats.kurtosis(samples)
print("Skewness", skewness)
print("Kurtosis", kurtosis)

Skewness 0.0024354210558467817
Kurtosis -0.004658942069704963


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [14]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [16]:
y = np.array([1, 3, 5, 6, 8, 5, 7, 6, 9, 10])
y

array([ 1,  3,  5,  6,  8,  5,  7,  6,  9, 10])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [38]:
r = np.corrcoef(x,y)
r

array([[1.        , 0.86732334],
       [0.86732334, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [39]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [40]:
stats.pearsonr(x, y) # Pearson's r

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [41]:
from scipy.stats import spearmanr

In [42]:
rho = spearmanr(x, y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

In [43]:
stats.spearmanr(x, y)   # Spearman's rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [21]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [22]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [24]:
tips.mode()

total_bill  tip   sex smoker  day    time  size
0       13.42  2.0  Male     No  Sat  Dinner     2

In [35]:
tips.median(numeric_only= True)

total_bill    17.795
tip            2.900
size           2.000
dtype: float64

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [34]:
tips.corr(method="pearson")

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

...
